name: "Tests"
on:
  pull_request:
    types: [edited, opened, reopened, synchronize]

jobs:
  build:
    steps:
      - uses: actions/checkout@v3
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - name: npm install
        run: npm ci --legacy-peer-deps
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test -- --coverage
      - run:
          name: Coverage Report
          command: bash <(curl -s https://codecov.io/bash)
